[package]
name = "noteiser"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.12", features = ["derive"] }
serde = "1.0.140"
serde_derive = "1.0.140"
toml = "0.5.9"
regex = "1.6.0"

[[bin]]
name = "ntsr"
path = "src/main.rs"
